/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AbortedRouteImport } from './routes/aborted'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as ConfirmedRouteImport } from './routes/confirmed'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as HotelsRouteImport } from './routes/hotels'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RolesRouteImport } from './routes/roles'
import { Route as TrashRouteImport } from './routes/trash'
import { Route as UsersRouteImport } from './routes/users'
import { Route as BookingTicketsAddRouteImport } from './routes/booking-tickets/add'
import { Route as BookingTicketsApprovedRouteImport } from './routes/booking-tickets/approved'
import { Route as BookingTicketsRecycleBinRouteImport } from './routes/booking-tickets/recycle-bin'
import { Route as BookingTicketsUnapprovedRouteImport } from './routes/booking-tickets/unapproved'
import { Route as BookingsIndexRouteImport } from './routes/bookings/index'
import { Route as QueriesIndexRouteImport } from './routes/queries/index'
import { Route as QueriesIdRouteImport } from './routes/queries/$id'
import { Route as QueriesNewRouteImport } from './routes/queries/new'
import { Route as BookingTicketsIdPrintRouteImport } from './routes/booking-tickets/$id.print'
import { Route as BookingsIdVoucherRouteImport } from './routes/bookings/$id.voucher'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AbortedRoute = AbortedRouteImport.update({
  id: '/aborted',
  path: '/aborted',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmedRoute = ConfirmedRouteImport.update({
  id: '/confirmed',
  path: '/confirmed',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelsRoute = HotelsRouteImport.update({
  id: '/hotels',
  path: '/hotels',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesRoute = RolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const TrashRoute = TrashRouteImport.update({
  id: '/trash',
  path: '/trash',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingTicketsAddRoute = BookingTicketsAddRouteImport.update({
  id: '/booking-tickets/add',
  path: '/booking-tickets/add',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingTicketsApprovedRoute = BookingTicketsApprovedRouteImport.update({
  id: '/booking-tickets/approved',
  path: '/booking-tickets/approved',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingTicketsRecycleBinRoute =
  BookingTicketsRecycleBinRouteImport.update({
    id: '/booking-tickets/recycle-bin',
    path: '/booking-tickets/recycle-bin',
    getParentRoute: () => rootRouteImport,
  } as any)
const BookingTicketsUnapprovedRoute =
  BookingTicketsUnapprovedRouteImport.update({
    id: '/booking-tickets/unapproved',
    path: '/booking-tickets/unapproved',
    getParentRoute: () => rootRouteImport,
  } as any)
const BookingsIndexRoute = BookingsIndexRouteImport.update({
  id: '/bookings/',
  path: '/bookings/',
  getParentRoute: () => rootRouteImport,
} as any)
const QueriesIndexRoute = QueriesIndexRouteImport.update({
  id: '/queries/',
  path: '/queries/',
  getParentRoute: () => rootRouteImport,
} as any)
const QueriesIdRoute = QueriesIdRouteImport.update({
  id: '/queries/$id',
  path: '/queries/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const QueriesNewRoute = QueriesNewRouteImport.update({
  id: '/queries/new',
  path: '/queries/new',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingTicketsIdPrintRoute = BookingTicketsIdPrintRouteImport.update({
  id: '/booking-tickets/$id/print',
  path: '/booking-tickets/$id/print',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsIdVoucherRoute = BookingsIdVoucherRouteImport.update({
  id: '/bookings/$id/voucher',
  path: '/bookings/$id/voucher',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aborted': typeof AbortedRoute
  '/accounts': typeof AccountsRoute
  '/calendar': typeof CalendarRoute
  '/confirmed': typeof ConfirmedRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRoute
  '/hotels': typeof HotelsRoute
  '/logs': typeof LogsRoute
  '/profile': typeof ProfileRoute
  '/roles': typeof RolesRoute
  '/trash': typeof TrashRoute
  '/users': typeof UsersRoute
  '/booking-tickets/add': typeof BookingTicketsAddRoute
  '/booking-tickets/approved': typeof BookingTicketsApprovedRoute
  '/booking-tickets/recycle-bin': typeof BookingTicketsRecycleBinRoute
  '/booking-tickets/unapproved': typeof BookingTicketsUnapprovedRoute
  '/queries/$id': typeof QueriesIdRoute
  '/queries/new': typeof QueriesNewRoute
  '/bookings/': typeof BookingsIndexRoute
  '/queries/': typeof QueriesIndexRoute
  '/booking-tickets/$id/print': typeof BookingTicketsIdPrintRoute
  '/bookings/$id/voucher': typeof BookingsIdVoucherRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aborted': typeof AbortedRoute
  '/accounts': typeof AccountsRoute
  '/calendar': typeof CalendarRoute
  '/confirmed': typeof ConfirmedRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRoute
  '/hotels': typeof HotelsRoute
  '/logs': typeof LogsRoute
  '/profile': typeof ProfileRoute
  '/roles': typeof RolesRoute
  '/trash': typeof TrashRoute
  '/users': typeof UsersRoute
  '/booking-tickets/add': typeof BookingTicketsAddRoute
  '/booking-tickets/approved': typeof BookingTicketsApprovedRoute
  '/booking-tickets/recycle-bin': typeof BookingTicketsRecycleBinRoute
  '/booking-tickets/unapproved': typeof BookingTicketsUnapprovedRoute
  '/queries/$id': typeof QueriesIdRoute
  '/queries/new': typeof QueriesNewRoute
  '/bookings': typeof BookingsIndexRoute
  '/queries': typeof QueriesIndexRoute
  '/booking-tickets/$id/print': typeof BookingTicketsIdPrintRoute
  '/bookings/$id/voucher': typeof BookingsIdVoucherRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aborted': typeof AbortedRoute
  '/accounts': typeof AccountsRoute
  '/calendar': typeof CalendarRoute
  '/confirmed': typeof ConfirmedRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRoute
  '/hotels': typeof HotelsRoute
  '/logs': typeof LogsRoute
  '/profile': typeof ProfileRoute
  '/roles': typeof RolesRoute
  '/trash': typeof TrashRoute
  '/users': typeof UsersRoute
  '/booking-tickets/add': typeof BookingTicketsAddRoute
  '/booking-tickets/approved': typeof BookingTicketsApprovedRoute
  '/booking-tickets/recycle-bin': typeof BookingTicketsRecycleBinRoute
  '/booking-tickets/unapproved': typeof BookingTicketsUnapprovedRoute
  '/queries/$id': typeof QueriesIdRoute
  '/queries/new': typeof QueriesNewRoute
  '/bookings/': typeof BookingsIndexRoute
  '/queries/': typeof QueriesIndexRoute
  '/booking-tickets/$id/print': typeof BookingTicketsIdPrintRoute
  '/bookings/$id/voucher': typeof BookingsIdVoucherRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aborted'
    | '/accounts'
    | '/calendar'
    | '/confirmed'
    | '/customers'
    | '/dashboard'
    | '/hotels'
    | '/logs'
    | '/profile'
    | '/roles'
    | '/trash'
    | '/users'
    | '/booking-tickets/add'
    | '/booking-tickets/approved'
    | '/booking-tickets/recycle-bin'
    | '/booking-tickets/unapproved'
    | '/queries/$id'
    | '/queries/new'
    | '/bookings/'
    | '/queries/'
    | '/booking-tickets/$id/print'
    | '/bookings/$id/voucher'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aborted'
    | '/accounts'
    | '/calendar'
    | '/confirmed'
    | '/customers'
    | '/dashboard'
    | '/hotels'
    | '/logs'
    | '/profile'
    | '/roles'
    | '/trash'
    | '/users'
    | '/booking-tickets/add'
    | '/booking-tickets/approved'
    | '/booking-tickets/recycle-bin'
    | '/booking-tickets/unapproved'
    | '/queries/$id'
    | '/queries/new'
    | '/bookings'
    | '/queries'
    | '/booking-tickets/$id/print'
    | '/bookings/$id/voucher'
  id:
    | '__root__'
    | '/'
    | '/aborted'
    | '/accounts'
    | '/calendar'
    | '/confirmed'
    | '/customers'
    | '/dashboard'
    | '/hotels'
    | '/logs'
    | '/profile'
    | '/roles'
    | '/trash'
    | '/users'
    | '/booking-tickets/add'
    | '/booking-tickets/approved'
    | '/booking-tickets/recycle-bin'
    | '/booking-tickets/unapproved'
    | '/queries/$id'
    | '/queries/new'
    | '/bookings/'
    | '/queries/'
    | '/booking-tickets/$id/print'
    | '/bookings/$id/voucher'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AbortedRoute: typeof AbortedRoute
  AccountsRoute: typeof AccountsRoute
  CalendarRoute: typeof CalendarRoute
  ConfirmedRoute: typeof ConfirmedRoute
  CustomersRoute: typeof CustomersRoute
  DashboardRoute: typeof DashboardRoute
  HotelsRoute: typeof HotelsRoute
  LogsRoute: typeof LogsRoute
  ProfileRoute: typeof ProfileRoute
  RolesRoute: typeof RolesRoute
  TrashRoute: typeof TrashRoute
  UsersRoute: typeof UsersRoute
  BookingTicketsAddRoute: typeof BookingTicketsAddRoute
  BookingTicketsApprovedRoute: typeof BookingTicketsApprovedRoute
  BookingTicketsRecycleBinRoute: typeof BookingTicketsRecycleBinRoute
  BookingTicketsUnapprovedRoute: typeof BookingTicketsUnapprovedRoute
  QueriesIdRoute: typeof QueriesIdRoute
  QueriesNewRoute: typeof QueriesNewRoute
  BookingsIndexRoute: typeof BookingsIndexRoute
  QueriesIndexRoute: typeof QueriesIndexRoute
  BookingTicketsIdPrintRoute: typeof BookingTicketsIdPrintRoute
  BookingsIdVoucherRoute: typeof BookingsIdVoucherRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aborted': {
      id: '/aborted'
      path: '/aborted'
      fullPath: '/aborted'
      preLoaderRoute: typeof AbortedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmed': {
      id: '/confirmed'
      path: '/confirmed'
      fullPath: '/confirmed'
      preLoaderRoute: typeof ConfirmedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotels': {
      id: '/hotels'
      path: '/hotels'
      fullPath: '/hotels'
      preLoaderRoute: typeof HotelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles': {
      id: '/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof RolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trash': {
      id: '/trash'
      path: '/trash'
      fullPath: '/trash'
      preLoaderRoute: typeof TrashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking-tickets/add': {
      id: '/booking-tickets/add'
      path: '/booking-tickets/add'
      fullPath: '/booking-tickets/add'
      preLoaderRoute: typeof BookingTicketsAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking-tickets/approved': {
      id: '/booking-tickets/approved'
      path: '/booking-tickets/approved'
      fullPath: '/booking-tickets/approved'
      preLoaderRoute: typeof BookingTicketsApprovedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking-tickets/recycle-bin': {
      id: '/booking-tickets/recycle-bin'
      path: '/booking-tickets/recycle-bin'
      fullPath: '/booking-tickets/recycle-bin'
      preLoaderRoute: typeof BookingTicketsRecycleBinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking-tickets/unapproved': {
      id: '/booking-tickets/unapproved'
      path: '/booking-tickets/unapproved'
      fullPath: '/booking-tickets/unapproved'
      preLoaderRoute: typeof BookingTicketsUnapprovedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings/': {
      id: '/bookings/'
      path: '/bookings'
      fullPath: '/bookings/'
      preLoaderRoute: typeof BookingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queries/': {
      id: '/queries/'
      path: '/queries'
      fullPath: '/queries/'
      preLoaderRoute: typeof QueriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queries/$id': {
      id: '/queries/$id'
      path: '/queries/$id'
      fullPath: '/queries/$id'
      preLoaderRoute: typeof QueriesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queries/new': {
      id: '/queries/new'
      path: '/queries/new'
      fullPath: '/queries/new'
      preLoaderRoute: typeof QueriesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking-tickets/$id/print': {
      id: '/booking-tickets/$id/print'
      path: '/booking-tickets/$id/print'
      fullPath: '/booking-tickets/$id/print'
      preLoaderRoute: typeof BookingTicketsIdPrintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings/$id/voucher': {
      id: '/bookings/$id/voucher'
      path: '/bookings/$id/voucher'
      fullPath: '/bookings/$id/voucher'
      preLoaderRoute: typeof BookingsIdVoucherRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AbortedRoute: AbortedRoute,
  AccountsRoute: AccountsRoute,
  CalendarRoute: CalendarRoute,
  ConfirmedRoute: ConfirmedRoute,
  CustomersRoute: CustomersRoute,
  DashboardRoute: DashboardRoute,
  HotelsRoute: HotelsRoute,
  LogsRoute: LogsRoute,
  ProfileRoute: ProfileRoute,
  RolesRoute: RolesRoute,
  TrashRoute: TrashRoute,
  UsersRoute: UsersRoute,
  BookingTicketsAddRoute: BookingTicketsAddRoute,
  BookingTicketsApprovedRoute: BookingTicketsApprovedRoute,
  BookingTicketsRecycleBinRoute: BookingTicketsRecycleBinRoute,
  BookingTicketsUnapprovedRoute: BookingTicketsUnapprovedRoute,
  QueriesIdRoute: QueriesIdRoute,
  QueriesNewRoute: QueriesNewRoute,
  BookingsIndexRoute: BookingsIndexRoute,
  QueriesIndexRoute: QueriesIndexRoute,
  BookingTicketsIdPrintRoute: BookingTicketsIdPrintRoute,
  BookingsIdVoucherRoute: BookingsIdVoucherRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
